sudo: required
language: java
jdk: oraclejdk8

services:
- docker


script:
- ./mvnw clean install -B


after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker-compose build
- docker-compose push

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: e-learning-system-app

before_install:
- chmod +x mvnw